# yaml-language-server: $schema=https://raw.githubusercontent.com/Kometa-Team/Kometa/nightly/json-schema/config-schema.json

#==================== KOMETA ====================#

#==================== kometa_emby2 ====================#
# kometa_emby2 config created by Quickstart on 2026-07-21 14:08:00
# System Information
# OS: Linux 7.0.0-22-generic
# Docker: True
# CPU: Unknown CPU (20 cores)
# Memory: 32845 MB / 46917 MB (70%) | 14071 MB Free
# Python: 3.13.14
# Git: Unavailable
# Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/26.5.2 Safari/605.1.15
# Quickstart Port: 7171
# Quickstart Debug: Disabled
# Quickstart Theme: emby
# Quickstart Optimize Template Defaults: Enabled
# Quickstart Config Archive History: Keep all (0)
# Quickstart Kometa Log Retention: Keep all (0)
# Quickstart ImageMaid Log Retention: Keep all (0)
# Quickstart Test Libraries Temp Path: /config/tmp
# Quickstart Test Libraries Install Path: /config/plex_test_libraries
# Quickstart Session Lifetime Days: 30
# Connected to Plex server Emre-Plex version 1.43.3.10828-00f62d37d
# Running on Linux version 7.0.0-22-generic
# Plex DB cache setting: 40 MB
# PlexPass: False on Public update channel.
# Scheduled maintenance running between 2:00 and 5:00
# Quickstart: 0.10.4 | Branch: master | Environment: Docker
###
# Libraries configured with Quickstart: 1 movie, 2 show
# Information on library: Filme
# Type: Movie
# Agent: tv.plex.agents.movie
# Scanner: Plex Movie
# Ratings Source: Rotten Tomatoes
# Content Count: 512 movies
# 
# Information on library: Animes
# Type: Show
# Agent: tv.plex.agents.series
# Scanner: Plex TV Series
# Ratings Source: N/A
# Content Count: 85 shows / 4427 episodes
# 
# Information on library: Serien
# Type: Show
# Agent: tv.plex.agents.series
# Scanner: Plex TV Series
# Ratings Source: N/A
# Content Count: 80 shows / 3237 episodes
### 
# We highly recommend using Visual Studio Code with indent-rainbow by oderwat extension and YAML by Red Hat extension. Visual Studio Code will also leverage the above link (yaml-language-server) to enhance Kometa yml edits.
###

# This file is auto-generated by Quickstart. Do not edit manually unless you know what you are doing.
#==================== kometa_emby2 ====================#


#==================== Libraries ====================#
# validation: validated (last_validated: 2026-07-21 11:02:55)
libraries:
#==================== Filme ====================#
  Filme:
    template_variables:
      sep_style: gold
      placeholder_imdb_id: tt15239678
      language: de
#==================== Collections ====================#
    collection_files:
    - default: separator_award
    - default: separator_chart
    - default: basic
    - default: imdb
      template_variables:
        use_lowest: false
    - default: letterboxd
      template_variables:
        use_afi_100: false
        use_boxofficemojo_100: false
        use_cannes: false
        use_edgarwright: false
        use_imdb_top_250: false
        use_international: false
        use_science: false
        use_western: false
        use_silent: false
        use_million: false
        use_oscars: false
        use_rogerebert: false
        use_sight_sound: false
        use_animation: false
        use_black_directors: false
        use_documentaries: false
        use_horror: false
        use_most_fans: false
        use_women_directors: false
        collection_order: critic_rating.desc
    - default: other_chart
      template_variables:
        use_commonsense: false
        use_stevenlu: false
        radarr_add_missing_pirated: true
        collection_order: user_rating.desc
    - default: actor
      template_variables:
        style: signature
        exclude:
        - Mayumi Tanaka
        - Ryō Horikawa
        - Masako Nozawa
        - Megumi Hayashibara
        - Rica Matsumoto
        - Shin-ichiro Miki
        - Toshio Furukawa
        - Yuji Ueda
        - Ikue Otani
        - Inuko Inuyama
        data:
          depth: 25
    - default: director
      template_variables:
        style: diiivoy
        exclude:
        - Wilson Yip
        - Daisuke Nishio
        - Shigeyasu Yamauchi
        - Yoshihiro Ueda
        data:
          depth: 10
          limit: 20
    - default: streaming
      template_variables:
        use_bet: false
        use_channel4: false
        use_crave: false
        use_crunchyroll: false
        use_discovery: false
        use_hayu: false
        use_hulu: false
        use_itvx: false
        use_hbomax: false
        use_now: false
        use_peacock: false
        use_youtube: false
        use_tubi: false
#==================== Overlays ====================#
    overlay_files:
    - default: ratings
      template_variables:
        rating1: user
        rating1_image: rt_popcorn
        rating1_font: config/fonts/LibreFranklin-Bold.ttf
        rating1_font_size: 45
        rating1_horizontal_offset: 846
        rating1_vertical_offset: 120
        rating2: critic
        rating2_image: rt_tomato
        rating2_font: config/fonts/LibreFranklin-Bold.ttf
        rating2_font_size: 45
        rating2_horizontal_offset: 846
        rating2_vertical_offset: 325
        rating3: audience
        rating3_image: imdb
        rating3_font: config/fonts/Roboto-Medium.ttf
        rating3_font_size: 45
        rating3_horizontal_offset: 846
        rating3_vertical_offset: 530
        horizontal_position: left
        vertical_position: center
        back_width: 130
        back_padding: 11
    - default: audio_codec
    - default: resolution
      template_variables:
        use_edition: true
    - default: streaming
      template_variables:
        horizontal_offset: 680
        vertical_offset: 10
    settings:
      asset_directory:
      - /assets/Filme
      prioritize_assets: true
    operations:
      assets_for_all: true
      mass_added_at_update:
      - tmdb
      - omdb
      - mdb_digital
      - mal
      - lock
      mass_audience_rating_update:
      - mdb_tomatoesaudience
      - tmdb
      - imdb
      mass_critic_rating_update:
      - mdb_tomatoes
      - omdb_tomatoes
      - imdb
      mass_user_rating_update:
      - imdb
      - tmdb
#==================== Animes ====================#
  Animes:
    template_variables:
      sep_style: navy
      placeholder_imdb_id: tt2560140
      language: de
#==================== Collections ====================#
    collection_files:
    - default: separator_award
    - default: separator_chart
    - default: imdb
      template_variables:
        use_top: false
    - default: myanimelist
      template_variables:
        use_favorited: false
        collection_order: episode_release.desc
    - default: studio
      template_variables:
        sort_by: critic_rating.desc
#==================== Overlays ====================#
    overlay_files:
    - default: status
      template_variables:
        text_airing: LÄUFT AKTUELL
        text_returning: FORTS. FOLGT
        text_canceled: ABGESETZT
        text_ended: ABGESCHLOSSEN
        font_size: 45
        back_color_airing: '#016920FF'
        back_color_returning: '#81007FFF'
        back_color_canceled: '#B52222FF'
        back_color_ended: '#000847FF'
        horizontal_offset: 430
        vertical_offset: 15
    - default: ratings
      template_variables:
        rating1: user
        rating1_image: imdb
        rating1_font: config/fonts/Roboto-Medium.ttf
        rating1_font_size: 45
        rating1_horizontal_offset: 831
        rating1_vertical_offset: 125
        rating2: critic
        rating2_image: anidb
        rating2_font: config/fonts/Arimo-Medium.ttf
        rating2_font_size: 45
        rating2_horizontal_offset: 831
        rating2_vertical_offset: 330
        rating3: audience
        rating3_image: mal
        rating3_font: config/fonts/Lato-Regular.ttf
        rating3_font_size: 45
        rating3_horizontal_offset: 831
        rating3_vertical_offset: 535
        horizontal_position: left
        vertical_position: center
        back_height: 150
        back_width: 150
        back_padding: 11
    - default: ratings
      template_variables:
        builder_level: episode
        rating1: critic
        rating1_image: imdb
        rating1_font: config/fonts/Roboto-Medium.ttf
        rating2: audience
        rating2_image: trakt
        rating2_font: config/fonts/Figtree-Medium.ttf
        horizontal_position: right
        vertical_position: center
    - default: resolution
      template_variables:
        use_edition: true
    - default: resolution
      template_variables:
        builder_level: season
        use_edition: true
    - default: resolution
      template_variables:
        builder_level: episode
        use_edition: true
    - default: streaming
      template_variables:
        horizontal_offset: 685
        vertical_offset: 10
    - default: video_format
      template_variables:
        builder_level: season
        horizontal_offset: 506
        vertical_offset: 1380
    - default: audio_codec
      template_variables:
        builder_level: episode
    operations:
      mass_studio_update:
      - mal
      - anidb
      - lock
      mass_audience_rating_update:
      - mal
      - anidb_average
      - imdb
      mass_critic_rating_update:
      - anidb_rating
      - mal
      - imdb
      mass_user_rating_update:
      - imdb
      - mal
      - anidb_average
      mass_episode_audience_rating_update:
      - trakt
      - imdb
      mass_episode_critic_rating_update:
      - imdb
      - trakt
      mass_episode_user_rating_update:
      - trakt
      - imdb
#==================== Serien ====================#
  Serien:
    template_variables:
      sep_style: aqua
      placeholder_imdb_id: tt0903747
      language: de
#==================== Collections ====================#
    collection_files:
    - default: separator_award
    - default: separator_chart
    - default: basic
    - default: imdb
      template_variables:
        use_top: false
        use_lowest: false
    - default: trakt
      template_variables:
        use_popular: false
        use_recommended: false
        use_watched: false
    - default: actor
      template_variables:
        style: signature
        data:
          limit: 10
    - default: streaming
      template_variables:
        use_bet: false
        use_channel4: false
        use_crave: false
        use_crunchyroll: false
        use_discovery: false
        use_hayu: false
        use_hulu: false
        use_itvx: false
        use_now: false
        use_peacock: false
        use_youtube: false
        use_tubi: false
#==================== Overlays ====================#
    overlay_files:
    - default: status
      template_variables:
        text_airing: LÄUFT AKTUELL
        text_returning: FORTS. FOLGT
        text_canceled: ABGESETZT
        text_ended: ABGESCHLOSSEN
        font: config/fonts/Figtree-Bold.ttf
        font_size: 45
        back_color_airing: '#016920FF'
        back_color_returning: '#81007FFF'
        back_color_canceled: '#B52222FF'
        back_color_ended: '#000847FF'
        back_width: 400
        horizontal_offset: 465
        vertical_offset: 15
    - default: ratings
      template_variables:
        rating1: user
        rating1_image: imdb
        rating1_font: config/fonts/Roboto-Medium.ttf
        rating1_font_size: 45
        rating1_horizontal_offset: 846
        rating1_vertical_offset: 120
        rating2: critic
        rating2_image: rt_tomato
        rating2_font: config/fonts/LibreFranklin-Bold.ttf
        rating2_font_size: 45
        rating2_horizontal_offset: 846
        rating2_vertical_offset: 325
        rating3: audience
        rating3_image: rt_popcorn
        rating3_font: config/fonts/LibreFranklin-Bold.ttf
        rating3_font_size: 45
        rating3_horizontal_offset: 846
        rating3_vertical_offset: 530
        horizontal_position: left
        vertical_position: center
        back_width: 130
        back_padding: 11
    - default: ratings
      template_variables:
        builder_level: episode
        rating1: critic
        rating1_image: imdb
        rating1_font: config/fonts/Roboto-Medium.ttf
        rating1_horizontal_offset: 25
        rating2: user
        rating2_image: trakt
        rating2_font: config/fonts/Figtree-Medium.ttf
        rating2_horizontal_offset: 25
        horizontal_position: right
        vertical_position: center
    - default: resolution
      template_variables:
        use_edition: true
    - default: resolution
      template_variables:
        builder_level: season
        use_edition: true
    - default: resolution
      template_variables:
        builder_level: episode
        use_edition: true
    - default: streaming
      template_variables:
        horizontal_offset: 680
        vertical_offset: 10
    - default: audio_codec
      template_variables:
        builder_level: season
    - default: audio_codec
      template_variables:
        builder_level: episode
    - default: video_format
      template_variables:
        builder_level: season
    operations:
      mass_audience_rating_update:
      - mdb_tomatoesaudience
      - imdb
      - tmdb
      mass_critic_rating_update:
      - mdb_tomatoes
      - imdb
      - tmdb
      mass_user_rating_update:
      - imdb
      - tmdb
      mass_episode_audience_rating_update:
      - imdb
      - trakt
      mass_episode_critic_rating_update:
      - imdb
      - trakt
      mass_episode_user_rating_update:
      - trakt
      - imdb

#==================== Settings ====================#
# validation: validated (last_validated: 2026-07-21 11:02:55)
settings:
  asset_depth: 0
  asset_directory:
  - config/assets
  asset_folders: true
  cache: true
  cache_expiration: 60
  create_asset_folders: true
  custom_repo:
  default_collection_order: release
  delete_below_minimum: true
  delete_not_scheduled: false
  dimensional_asset_rename: false
  download_url_assets: false
  ignore_ids: 
  ignore_imdb_ids:
  item_refresh_delay: 0
  minimum_items: 1
  missing_only_released: false
  only_filter_missing: false
  overlay_artwork_filetype: png
  overlay_artwork_quality: 90
  overlay_refresh_emby_items: true
  playlist_exclude_users:
  playlist_report: false
  playlist_sync_to_users:
  prioritize_assets: true
  run_again_delay: 2
  run_order:
  - operations
  - metadata
  - collections
  - overlays
  save_report: false
  server_type: emby
  show_asset_not_needed: true
  show_filtered: false
  show_missing: true
  show_missing_assets: true
  show_missing_episode_assets: false
  show_missing_season_assets: false
  show_options: true
  show_unconfigured: true
  show_unfiltered: false
  show_unmanaged: true
  sync_mode: append
  tvdb_language: ger
  verify_ssl: true

#==================== Webhooks ====================#
# validation: validated (last_validated: 2026-07-21 11:02:55)
webhooks:
  changes: notifiarr
  error: notifiarr
  run_end: notifiarr

#==================== Emby ====================#
# validation: validated (last_validated: 2026-07-21 11:02:53)
emby:
  api_key: 
  db_cache: 64
  overlay_destination_folder: /var/lib/emby/plugins/kometa
  timeout: 60
  url: http://YOUR_IP:8096
  user_id: 
  verify_ssl: false

#==================== Plex ====================#
# validation: validated (last_validated: 2026-07-21 11:02:53)
plex:
  clean_bundles: false
  db_cache: 40
  empty_trash: false
  optimize: false
  timeout: 60
  token: 
  url: http://YOUR_IP:32400
  verify_ssl: true

#==================== TMDb ====================#
# validation: validated (last_validated: 2026-07-21 11:02:53)
tmdb:
  apikey: 
  cache_expiration: 60
  language: de
  region: DE

#==================== TVDb ====================#
# validation: validated (last_validated: 2026-07-21 11:02:54)
tvdb:
  apikey: 
  cache_expiration: 30
  language: 
  pin:

#==================== OMDb ====================#
# validation: validated (last_validated: 2026-07-21 11:02:53)
omdb:
  apikey: 
  cache_expiration: 60

#==================== MDBList ====================#
# validation: validated (last_validated: 2026-07-21 11:02:54)
mdblist:
  apikey: 
  cache_expiration: 60

#==================== Notifiarr ====================#
# validation: validated (last_validated: 2026-07-21 11:02:55)
notifiarr:
  apikey: 

#==================== AniDB ====================#
# validation: validated (last_validated: 2026-07-21 11:02:55)
anidb:
  cache_expiration: 60
  enable_mature: false
  language: 

#==================== Radarr ====================#
# validation: validated (last_validated: 2026-07-21 11:02:55)
radarr:
  add_existing: false
  add_missing: false
  availability: released
  ignore_cache: false
  monitor: true
  monitor_existing: false
  plex_path: 
  quality_profile: ''
  radarr_path: 
  root_folder_path: 
  search: true
  tag:
  token: 
  upgrade_existing: false
  url: http://YOUR_IP:7878

#==================== Sonarr ====================#
# validation: validated (last_validated: 2026-07-21 11:02:55)
sonarr:
  add_existing: false
  add_missing: false
  cutoff_search: false
  ignore_cache: false
  language_profile: Original
  monitor: all
  monitor_existing: false
  plex_path:
  quality_profile: ''
  root_folder_path: 
  search: true
  season_folder: true
  series_type: standard
  sonarr_path: 
  tag: anime
  token: 
  upgrade_existing: false
  url: http://YOUR_IP:8989

#==================== Trakt ====================#
# validation: validated (last_validated: 2026-07-21 11:02:55)
trakt:
  authorization:
    access_token:
    created_at: 
    expires_in: 
    refresh_token: 
    scope: public offline_access
    token_type: bearer
  client_id: 
  client_secret: 
  pin:
  force_refresh: false

#==================== MyAnimeList ====================#
# validation: validated (last_validated: 2026-07-21 11:02:55)
mal:
  authorization:
    access_token: 
    expires_in: 
    refresh_token: 
    token_type: Bearer
  cache_expiration: 60
  client_id: 
  client_secret: 
  localhost_url: 
